### PR TITLE
Extends GitLab CI scripts to run different compiler versions

### PR DESCRIPTION
**Pull request by SimeonEhrig**
Address the Issue #171. It runs over different GCC, Clang, Boost and CUDA versions.

Different versions will be build in single job (and runner), because a single test configuration needs just a few time for building and running and the overhead of pulling the docker image would becomes huge. However, the configuration is flexible. It is also possible to divide a heavy job and more lightweight jobs. For example, the `GCC` is divided in 3 jobs. Otherwise, they would run in a time out.

Issue #173 is also solved in this PR.

### CODE REVIEW

**Comment by SimeonEhrig** [comment]
@psychocoderHPC 
Ready for merge and blowing up the CI infrastructure ;-)

**Comment by sbastrakov** [comment]
@SimeonEhrig I can also merge cupla stuff. One question: is it meant to go to `master` or `dev` branch? (your PR is currently to master)

**Comment by SimeonEhrig** [comment]
The PR should merged in the `master`, because my last commit with changes for the CI was also merged in `master`. But I'm not sure if the last RP was not already merged in the wrong branch. Anyway, this PR does not changes the application code itself, so it should be not a problem to rebase the dev branch and use the new infrastructure in both branches.

**Comment by psychocoderHPC** [comment]
I will close this PR that it is not merged by accident. The PR is opened against the master, we never merge directly into the master.

**Pull request closed without merging**
