### PR TITLE
Change docker images for GitLab CI tests

### PR DESCRIPTION
**Pull request by SimeonEhrig**
New container generator for the GitLab CI tests.
See: https://gitlab.com/hzdr/crp/alpaka-group-container

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
We should check if we can handle https://gitlab.com/hzdr/crp/cupla/-/jobs/551865986#L292 via an boost define. We should check CUDA 9.1 and CUDA 9.2 too. If only CUDA 9.0 is showing the issue I am fine with remove support for CUDA 9.0 in CUPLA.

**Comment by SimeonEhrig** [comment]
@psychocoderHPC 
The refactoring is finish. Now it ready for merge but we can also add some more test cases. [Here](https://gitlab.com/hzdr/crp/alpaka-group-container/-/blob/master/generator/generator.py) you can see the available Software Versions.

**Comment by SimeonEhrig** [comment]
> We should check if we can handle https://gitlab.com/hzdr/crp/cupla/-/jobs/551865986#L292 via an boost define. We should check CUDA 9.1 and CUDA 9.2 too. If only CUDA 9.0 is showing the issue I am fine with remove support for CUDA 9.0 in CUPLA.

CUDA 9.1 has the same bug. CUDA 9.2 is fine.

**Comment by SimeonEhrig** [comment]
@psychocoderHPC 
When travis is finish, the PR is ready for merge. Also look for minimum CUDA version but I didn't found any hint in the documentation or checks in the cmake files.

**Comment by psychocoderHPC** [comment]
ohh no this PR is against master.

**Pull request merged**
