### PR TITLE
Topic update to latest alpaka release 0.6.1

### PR DESCRIPTION
**Pull request by psychocoderHPC**
Update to alpaka 0.6.1

```
GIT_AUTHOR_NAME="Third Party" GIT_AUTHOR_EMAIL="cupla@hzdr.de" git subtree pull --prefix alpaka git@github.com:alpaka-group/alpaka.git 0.6.1 --squash
```

### CODE REVIEW

**Review by sbastrakov — APPROVED** [review]

**Review by sbastrakov — COMMENTED** [review]
Not sure, should the alpaka version in the readme have been bumped?

**Review by j-stephan — CHANGES_REQUESTED** [review]
@sbastrakov Yup, thanks for noticing.

**Comment by psychocoderHPC** [comment]
> Not sure, should the alpaka version in the readme have been bumped?

well spotted

**Comment by psychocoderHPC** [comment]
@sbastrakov Readme is now updated too.

**Review by sbastrakov — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
@sbastrakov Could you please merge

**Pull request merged**
