### PR TITLE
CI: update container to v1.1

### PR DESCRIPTION
**Pull request by psychocoderHPC**
Use latest container for testing.

### CODE REVIEW

**Comment by j-stephan** [comment]
Looks like CUDA 9.2 is unhappy about using GCC 5.5.0.

**Comment by psychocoderHPC** [comment]
> Looks like CUDA 9.2 is unhappy about using GCC 5.5.0.

I will check this, we saw similar errors with 5.X in the past. 
I checked the last PR which we merged and for some reason the last time gcc 5.4.0 was used and not 5.5 https://gitlab.com/hzdr/crp/cupla/-/jobs/867294947#L1946

**Comment by psychocoderHPC** [comment]
Error is coming from a gcc issue: https://stackoverflow.com/a/50815334

I am thinking now about removing gcc 5.5 in combination with cuda 9.2 from the test

**Comment by psychocoderHPC** [comment]
we hande the avx issue in the alpaka tests https://github.com/alpaka-group/alpaka/blob/57f14c31417bc26af4164983a9de81e2e8e2ecaf/script/before_install.sh#L99-L101 therefor I will remove the tests here

**Review by j-stephan — APPROVED** [review]

**Pull request merged**
